# Generated by Django 2.0.1 on 2018-04-06 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tag', models.SlugField()),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 4, 6, 12, 34, 0, 161368))),
                ('organiser', models.CharField(max_length=32)),
                ('contact', models.EmailField(default='abc@gmail.com', max_length=254)),
            ],
        ),
    ]
