# Generated by Django 2.0.3 on 2018-04-03 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180403_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.EmailField(default='to1@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2018, 4, 3)),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='#description_default_text'),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.SlugField(default='django-db-models-fields-charfield', max_length=32, unique=True),
        ),
    ]
