# Generated by Django 2.0.3 on 2018-04-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180403_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.SlugField(unique=True),
        ),
    ]
