# Generated by Django 2.0.3 on 2018-04-03 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180403_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 3, 12, 37, 0, 484110, tzinfo=utc)),
        ),
    ]
