# Generated by Django 2.0.3 on 2018-04-03 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180403_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 4, 3, 12, 38, 6, 539600, tzinfo=utc)),
        ),
    ]
