# Generated by Django 2.0.3 on 2018-04-03 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180403_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tag',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 18, 27, 33, 801718)),
        ),
    ]
