# Generated by Django 2.0.3 on 2018-04-03 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20180403_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 19, 29, 0, 672032)),
        ),
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.CharField(max_length=32),
        ),
    ]
