# Generated by Django 2.0.1 on 2018-04-15 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180415_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.CharField(choices=[('Swayam', 'Swayam'), ('EcoClub', 'Eco Club'), ('ArtsClub', 'Arts club'), ('Abhinay', 'Abhinay'), ('ThemeBallet', 'Theme Ballet'), ('VCETalkies', 'Vasavi talkies'), ('CSI', 'CSI')], max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 15, 22, 30, 43, 236674)),
        ),
    ]
