# Generated by Django 2.0.3 on 2018-04-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180411_2302'),
        ('events', '0005_auto_20180411_0048'),
    ]

    operations = [
    ]
