# Generated by Django 2.0.3 on 2018-04-03 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180403_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='slug',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 19, 30, 32, 132388)),
        ),
    ]
