# Generated by Django 2.0.3 on 2018-04-04 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20180403_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 9, 54, 46, 24370)),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.SlugField(),
        ),
    ]
