# Generated by Django 2.0.3 on 2018-04-05 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20180406_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 1, 27, 40, 985590)),
        ),
    ]
