# Generated by Django 2.0.1 on 2018-04-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=500),
        ),
    ]
