# Generated by Django 2.0.1 on 2018-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180406_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id_of_answer',
            field=models.IntegerField(default=0),
        ),
    ]
