# Generated by Django 2.0.3 on 2018-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180411_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('organizer', 'ORGANIZER'), ('participant', 'PARTICIPANT')], default='participant', max_length=12),
        ),
    ]
