# Generated by Django 2.0.3 on 2018-04-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180411_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_organizer',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_participant',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('organizer', 'ORGANIZER'), ('participant', 'PARTICIPANT')], default='participant', max_length=12),
        ),
    ]
