# Generated by Django 2.0.3 on 2018-04-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180411_0048'),
        ('accounts', '0006_userprofile_phone'),
    ]

    operations = [
    ]
